### HOME
GET http://localhost:5001/

### /productos
GET http://localhost:5001/productos

### crear producto 
POST http://localhost:5001/productos
Content-Type: application/json

{
    "nombre": "producto c",
    "cantidad": 5,
    "precio": 12
}

### modificar producto 
PUT http://localhost:5001/productos/4
Content-Type: application/json

{
    "nombre": "producto 3",
    "precio": 12,
    "cantidad": 10
}


### eliminar producto 
DELETE http://localhost:5001/productos/2

### get unique /productos
GET http://localhost:5001/productos/2

##filtro
GET http://localhost:5001/productos?filtro=libro